country=GB
ap_scan=1

# This example uses dynamic configuration to demonstrate the usage of WpaClient
# interface. Refer to client.conf to set up the network information.
#
# Refer to wpa_supplicant.conf documentation for more information on possible
# values in this file. You can usually find an example configuration file with
# extensive comments in /usr/share/doc/wpa_supplicant/wpa_supplicant.conf or
# similar location depending on your distribution.
